### ISSUE TITLE
PMD Pico Camera Settings

### ISSUE THREAD

**Issue by DeepAnonymous** [yaorong0921/GeScale#1]
Hi @yaorong0921 , @okankop 

Thank you for sharing this amazing code & the SHGD dataset.

I just bought a Pico camera and would like to capture some video sequences to test. However, I don't know what were the specs that you used to capture the SHGD dataset. 

I just used Royale Viewer to display gray & depth images, but they look quite different from those in the dataset. Specifically, could you please give me some insights:

Color Range (for Gray): min Value? max Value?
Color Range (for IR) distance min Value? distance max Value?
Use Case (FPS):
Exposure Time:
Filter level:
Filter (Min/Max):
Distance from the camera to subjects when capturing:

Thank you very much in advanced.

Sincerely,

**Comment by DeepAnonymous** [comment]
Is it possible to public the code capturing images from PMD camera (IR + depth)?

This would be really helpful for all researchers.

Thank you.

**Comment by yaorong0921** [comment]
> Hi @yaorong0921 , @okankop
> 
> Thank you for sharing this amazing code & the SHGD dataset.
> 
> I just bought a Pico camera and would like to capture some video sequences to test. However, I don't know what were the specs that you used to capture the SHGD dataset.
> 
> I just used Royale Viewer to display gray & depth images, but they look quite different from those in the dataset. Specifically, could you please give me some insights:
> 
> Color Range (for Gray): min Value? max Value?
> Color Range (for IR) distance min Value? distance max Value?
> Use Case (FPS):
> Exposure Time:
> Filter level:
> Filter (Min/Max):
> Distance from the camera to subjects when capturing:
> 
> Thank you very much in advanced.
> 
> Sincerely,

Dear DeepAnonymous,
thank you very much for your interest. When using the Royale Viewer, you have the color overlay features. But we extracted the picture directly from camera without using any of this features. You can find the sample code for acquiring the data using different platforms from the pmd packages as well.  


In our process, we set the use mode with 45 fps and exposure time with 400ms (MODE_5_45FPS_400) for the Pico Monstar.

**Comment by yaorong0921** [comment]
> Is it possible to public the code capturing images from PMD camera (IR + depth)?
> 
> This would be really helpful for all researchers.
> 
> Thank you.

Sure, Let me show your some useful code from our data acquisition:
(I used a python script):

1. Get the camera instance and set the use case for it.
```   cameras = tof.Camera.listCameras()
    print(cameras)
    camera = tof.Camera.createCamera(cameras[0])
    use_cases = camera.getUseCases()
    camera.setUseCase(b'MODE_5_45FPS_400')
    print('usecases', use_cases)
    print('frame rate', camera.getFrameRate())
```

2. Get the data for every frame, grayscale value and depth..
  ```  # get frames from camera
        frames = camera.getFrameGenerator(array_only=True)
        # get data from frames
        for data in frames:
            w, h, points = data
            frame = np.reshape(points, [h, w, 3])
            data_queue.put(frame)
            # get the conf matrix to filter out some not confident points
            conf = frame[:, :, 2]
            conf[np.where(conf < conf_value)] = 0
            conf[np.where(conf >= conf_value)] = 1

            # frame 1 = depth image; frame 2 = grayscale images
            frame1 = frame[:, :, 0]
            # set the max.distance for capturing
            frame1[np.where(frame1 >= depth_value)] = 0
            frame1 = np.multiply(frame1, conf)
            frame1 = np.array(frame1 * 255, dtype='uint8')
            frame1 = cv2.flip(frame1, 1)

            frame2 = frame[:, :, 1]
            frame2 = np.array(frame2 * np.max(255.0 / (frame2.max() - frame2.min()), 0), dtype='uint8')
            frame2 = cv2.flip(frame2, 1)
```
From here, you can set the max.distance and filter out the unsure points..

We made some modifications for the function like `camera.getFrameGenerator()` for our own use case, which could be a bit different from the function from the pmd pachages. 
I hope it helps you. If you have any other questions, iam glad to help.

Best regards,

**Comment by DeepAnonymous** [comment]
Hi @yaorong0921 ,

Thank you very much for your reply.  I really appreciate that.

Let's me try first to see if there is any further questions.

Again, the code is amazing. Thanks for sharing.

**Comment by DeepAnonymous** [comment]
Dear @yaorong0921 ,

Thanks to your help, I was able to capture both IR and depth data.

However, there are two remaining issues I hope you could provide some further insights.

1. Could you please provide more specific settings of the parameters `conf_value `and `depth_value` (max.distance)? The reason is that I hope my settings to be consistent with the SHGD dataset when capturing data for testing.

2. As I implemented the capturing function, I needed to use `roypy.IDepthDataListener` class by queuing them and using the `queue.get(True, 1)` function to retrieve an item from the queue. It's OK when capturing data only, but when I use this to capture and perform hand gesture in real-time, there is an error occurs (after few minutes).
- **AttributeError**: 'Queue" object has no attribute '_Empty_'.
- My guess is that the high temperature after long working time, but I'm not sure.

I'd be grateful if you could give your thought regarding these issues.

Thank you very much.

**Comment by yaorong0921** [comment]
> Dear @yaorong0921 ,
> 
> Thanks to your help, I was able to capture both IR and depth data.
> 
> However, there are two remaining issues I hope you could provide some further insights.
> 
> 1. Could you please provide more specific settings of the parameters `conf_value `and `depth_value` (max.distance)? The reason is that I hope my settings to be consistent with the SHGD dataset when capturing data for testing.
> 2. As I implemented the capturing function, I needed to use `roypy.IDepthDataListener` class by queuing them and using the `queue.get(True, 1)` function to retrieve an item from the queue. It's OK when capturing data only, but when I use this to capture and perform hand gesture in real-time, there is an error occurs (after few minutes).
> 
> * **AttributeError**: 'Queue" object has no attribute '_Empty_'.
> * My guess is that the high temperature after long working time, but I'm not sure.
> 
> I'd be grateful if you could give your thought regarding these issues.
> 
> Thank you very much.

Dear @DeepAnonymous,
Here are some thoughts regarding to your problems:
1. I used the configs 
``` # some parameters for images
    conf_value = 125
    depth_value = 1.5
```
to extract the images with little noise (in the background).

2. I suppose the error occurs because there are some frames missing, and the queue is empty when you want to process. As you said, it could be that the camera temperature is too high after a few minutes. I think one other possible reason for the error could be that the `roypy.IDepthDataListener` class is too slow when extracting the data. 
One suggestion for debugging this problem is that you can **calculate the real-time fps**. Then you can monitor how the fps changes. If it is always too low than expected, then it may be the problem of slow `roypy.IDepthDataListener` class. If it is because of the high temperature of camera, try to reboot the camera (`camera.stopCapture()` stops the camera) after several minutes can help.

Hope it helps your problems. Thank you for your interest again!

**Comment by DeepAnonymous** [comment]
Dear @yaorong0921 ,

Thank you very much for your reply.

Best regards,
